# Generated by Django 3.0.8 on 2020-07-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=40)),
                ('unit_number', models.IntegerField(default=0)),
                ('street', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('province', models.CharField(blank=True, max_length=40)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('zip_code', models.IntegerField(default=0)),
                ('landline_number', models.IntegerField(default=0)),
                ('mobile_number', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('job_title', models.CharField(blank=True, max_length=40)),
                ('employee_number', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('department', models.CharField(blank=True, max_length=40)),
                ('job_email', models.EmailField(blank=True, max_length=40)),
                ('salary', models.IntegerField(default=0)),
                ('sss', models.CharField(blank=True, max_length=40)),
                ('philhealth', models.CharField(blank=True, max_length=40)),
                ('pagibig', models.CharField(blank=True, max_length=40)),
                ('bir', models.CharField(blank=True, max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
