# Generated by Django 3.0.8 on 2020-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiV2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
